title: Project

fields:
    description:
        type: text
        label: Descriptoion

    employees:
        type: manytomany
        label: Employees
        fields:
            foreignkey:
                label: Employee
                type: multiselect
                min: 1
                max: 1
                options: query
                query:
                    fetch: site.find('employees').childrenAndDrafts
                    text: "{{ page.title }}"
                    value: "{{ page.autoid }}"
            hours:
                type: number
                label: Number of hours
        validate:
            unique: employees
        relatedTemplate: employee
        relatedPage: employees
        relatationField: projects
        
    autoid:
          translate: false